server.port=${SMS_SERVICE_PORT:8082}
spring.application.name=SmsService
spring.config.import=optional:file:./SmsService/.env.properties,optional:file:./.env.properties

textbee.api-key=35345798-8f45-4cfd-b8c2-e2085d1184ec
textbee.device-id=6a0ef49b9b9db0a6fe73f5a4
