import { test, expect } from '@playwright/test';

test('test2AllButtons', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('main').click();
  await page.getByRole('textbox', { name: 'EMAIL' }).click();
  await page.getByRole('textbox', { name: 'PASSWORD' }).click();
  await page.getByRole('textbox', { name: 'PASSWORD' }).fill('ParolaMarius');
  await page.getByRole('textbox', { name: 'EMAIL' }).click();
  await page.getByRole('textbox', { name: 'EMAIL' }).fill('mariustrif0323@yahoo.com');
  await page.getByRole('button', { name: 'INITIALIZE SESSION' }).click();


  await page.getByRole('button', { name: 'Upvote Data table sort breaks on null Last Active values' }).click();
  await page.getByRole('link', { name: '▱ 1 Comments' }).first().click();
  await page.getByRole('textbox', { name: 'Add a comment or suggest a' }).click();
  await page.getByRole('textbox', { name: 'Add a comment or suggest a' }).fill('Acesta este un peisaj frumos, dar irelevant');
  await page.getByRole('button', { name: 'Post Comment' }).click();
  await page.getByRole('button', { name: 'Post Comment' }).click();
  await page.getByRole('link', { name: 'Back to feed' }).click();
  await page.getByRole('link', { name: '▱ 0 Comments' }).click();
  await page.getByRole('textbox', { name: 'Add a comment or suggest a' }).click();
  await page.getByRole('textbox', { name: 'Add a comment or suggest a' }).fill('Acest bug nu are poza');
  await page.getByRole('button', { name: 'Post Comment' }).click();
  await page.getByRole('link', { name: 'Back to feed' }).click();
  await page.getByRole('link', { name: '▱ 1 Comments' }).first().click();
  await page.getByRole('button', { name: 'Upvote comment' }).click();
  await page.getByRole('link', { name: 'Back to feed' }).click();
  await page.getByRole('link', { name: '▱ 2 Comments' }).first().click();
  await page.getByRole('button', { name: 'Highest Votes' }).click();
  await page.pause();
  await page.getByRole('menuitem', { name: 'Lowest Votes' }).click();
  await page.getByText('Sort byLowest Votes').click();
  await page.pause();
  await page.getByRole('menuitem', { name: 'Newest' }).click();
  await page.getByRole('button', { name: 'Newest' }).click();
  await page.pause();
  await page.getByRole('menuitem', { name: 'Oldest' }).click();
  await page.getByRole('button', { name: 'Oldest' }).click();
  await page.pause();
  await page.getByRole('menuitem', { name: 'Highest Votes' }).click();
  await page.getByRole('link', { name: 'Back to feed' }).click();
  await page.getByRole('link', { name: 'My Profile' }).click();
  await page.getByRole('link', { name: 'Report Bug' }).click();
  await page.getByRole('textbox', { name: 'Bug title' }).click();
  await page.getByRole('textbox', { name: 'Bug title' }).fill('CreereBugInstagarm');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Am un bug care ma deranjeaza pe aplicatia Instagram. Nu mai pot da refresh din brawsers. Ce pot face?');
  await page.getByRole('textbox', { name: 'Screenshot / attachment' }).click();
  await page.getByRole('textbox', { name: 'Screenshot / attachment' }).fill('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZbNpZresF1hB-9eLNeXZsg1c42EGP48y6Yw&s');
  await page.getByRole('button', { name: 'Select tag...' }).click();
  await page.getByRole('menuitem', { name: 'frontend' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByText('Bug titleDescriptionAm un bug').click();
  await page.getByRole('button', { name: 'Post Bug' }).click();
  await page.getByRole('link', { name: '▱ 0 Comments' }).click();
  await page.getByRole('textbox', { name: 'Add a comment or suggest a' }).click();
  await page.getByRole('textbox', { name: 'Add a comment or suggest a' }).fill('Propriul comentariu');
  await page.getByRole('button', { name: 'Post Comment' }).click();
});